#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
vpn_configure.py - Generate strongSwan IKEv2 PSK server config + Android phone setup guide.

Phone uses built-in system VPN (Settings > VPN > Add > Type: IKEv2/IPSec PSK).
Pure pre-shared-key auth (no username/password, no certificate, no app).
Split tunnel: only game server IP through VPN.

Usage:
    python vpn_configure.py --server-ip <public_ip> [--output-dir <dir>]

Outputs:
    ipsec.conf      - strongSwan config (copy to /etc/ipsec.conf)
    ipsec.secrets   - strongSwan secrets (copy to /etc/ipsec.secrets)
    phone-setup.txt - step-by-step phone setup guide with the 3 fields to fill in
"""
from __future__ import print_function
import argparse
import os
import secrets


def generate_psk(length=20):
    return secrets.token_hex(length // 2)


def main():
    ap = argparse.ArgumentParser(description="Generate strongSwan IKEv2 PSK VPN config")
    ap.add_argument("--server-ip", required=True, help="Server public IP")
    ap.add_argument("--game-server-ip", default="47.96.0.227",
                    help="Game server IP for split tunnel (default: 47.96.0.227)")
    ap.add_argument("--output-dir", default=".",
                    help="Output directory for generated configs")
    ap.add_argument("--psk", help="Pre-shared key (auto-generated if omitted)")
    args = ap.parse_args()

    psk = args.psk or generate_psk()
    out = os.path.abspath(args.output_dir)
    os.makedirs(out, exist_ok=True)

    # --- ipsec.conf ---
    ipsec_conf = (
        "# strongSwan IKEv2 VPN server config\n"
        "# Generated by vpn_configure.py\n"
        "#\n"
        "# Full tunnel: ALL phone traffic via VPN.\n"
        "# Android's built-in VPN REQUIRES leftsubnet=0.0.0.0/0 — narrowing the\n"
        "# traffic selector (e.g. {game_ip}/32) makes the native client reject the\n"
        "# negotiated CHILD_SA and DELETE the tunnel right after IKE_AUTH succeeds.\n"
        "# Server-side split tunnel only works with the strongSwan app, not system VPN.\n"
        "\n"
        "config setup\n"
        "    charondebug=\"ike 2, knl 2, cfg 2\"\n"
        "    uniqueids=no\n"
        "\n"
        "conn mahjong-vpn\n"
        "    keyexchange=ikev2\n"
        "    ike=aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha256-ecp256,aes256-sha256-modp1024\n"
        "    esp=aes256-sha256,aes128-sha256\n"
        "    dpdaction=clear\n"
        "    dpddelay=30s\n"
        "    rekey=no\n"
        "    left=%any\n"
        "    leftid={server_ip}\n"
        "    leftsubnet=0.0.0.0/0\n"
        "    leftauth=psk\n"
        "    right=%any\n"
        "    rightauth=psk\n"
        "    rightsourceip=10.99.0.0/24\n"
        "    mobike=yes\n"
        "    auto=add\n"
    ).format(server_ip=args.server_ip, game_ip=args.game_server_ip)

    ipsec_conf_path = os.path.join(out, "ipsec.conf")
    with open(ipsec_conf_path, "w", encoding="utf-8") as f:
        f.write(ipsec_conf)
    print("[ok] Server config  -> {}".format(ipsec_conf_path))

    # --- ipsec.secrets ---
    ipsec_secrets = (
        "# strongSwan IKEv2 secrets\n"
        "# Generated by vpn_configure.py\n"
        "# The ': PSK' form (no leading ID) matches any %any road-warrior client.\n"
        ": PSK \"{psk}\"\n"
    ).format(psk=psk)

    ipsec_secrets_path = os.path.join(out, "ipsec.secrets")
    with open(ipsec_secrets_path, "w", encoding="utf-8") as f:
        f.write(ipsec_secrets)
    os.chmod(ipsec_secrets_path, 0o600)
    print("[ok] Server secrets -> {}".format(ipsec_secrets_path))

    # --- phone-setup.txt ---
    phone_setup = (
        "============================================================\n"
        "Phone VPN Setup (Android system VPN - no app needed)\n"
        "============================================================\n"
        "\n"
        "Only 3 fields to fill in. Pure pre-shared-key (PSK).\n"
        "NO username, NO password, NO certificate.\n"
        "\n"
        "1. Settings > Network & internet > VPN\n"
        "2. Tap \"+\" (Add VPN)\n"
        "3. Fill in EXACTLY these 3 fields:\n"
        "   Type (类型):                 IKEv2/IPSec PSK\n"
        "       ^^^ MUST be PSK. NOT \"IKEv2/IPSec RSA\" (certificate),\n"
        "           NOT \"IKEv2/IPSec MSCHAPv2\". Wrong type = can't connect.\n"
        "   Server (服务器):             {server_ip}\n"
        "   Pre-shared key (预共享密钥): {psk}\n"
        "\n"
        "   IPSec identifier (标识符):   LEAVE EMPTY (留空)\n"
        "   Username / Password:         DO NOT FILL (不要填用户名/密码)\n"
        "   Name (名称):                 Mahjong (anything you like)\n"
        "\n"
        "4. Tap Save\n"
        "5. Tap the gear icon next to the VPN entry\n"
        "6. Enable \"Always-on VPN\" = ON\n"
        "7. Done! Phone will auto-connect on any network forever.\n"
        "\n"
        "NOTE: If you previously created an old entry with Type RSA /\n"
        "certificate, DELETE it first, then add a new one as above.\n"
        "\n"
        "Full tunnel: ALL phone traffic goes through the VPN.\n"
        "(Android's built-in VPN does not support server-side split tunnel;\n"
        " WeChat/browser also route via the cloud server while VPN is on.)\n"
        "============================================================\n"
    ).format(server_ip=args.server_ip, psk=psk,
             game_ip=args.game_server_ip)

    phone_setup_path = os.path.join(out, "phone-setup.txt")
    with open(phone_setup_path, "w", encoding="utf-8") as f:
        f.write(phone_setup)
    print("[ok] Phone guide   -> {}".format(phone_setup_path))

    print("")
    print("=== Configuration Summary ===")
    print("Server IP       : {}".format(args.server_ip))
    print("Split Tunnel    : only {} routed through VPN".format(args.game_server_ip))
    print("PSK             : {}".format(psk))
    print("Auth            : pure PSK (no username/password)")
    print("Phone subnet    : 10.99.0.0/24")
    print("")
    print("Next steps:")
    print("  1. Copy ipsec.conf to /etc/ipsec.conf on the server")
    print("  2. Copy ipsec.secrets to /etc/ipsec.secrets on the server")
    print("  3. Run: ipsec restart")
    print("  4. On phone: Settings > VPN > Add (see phone-setup.txt)")


if __name__ == "__main__":
    main()
