#!/usr/bin/env python3
"""
package_extractor.py — 在开发机上把 extractor 打包成软路由可独立运行的 bundle

产出 mahjong-extractor-bundle.tar.gz，内含 extractor 运行所需的最小模块集
（实测依赖链，不含 cv2/numpy/PyQt），以及安装脚本与服务文件。

用法（在项目根或 remote/extractor/ 下均可）：
    python remote/extractor/package_extractor.py [-o 输出路径.tar.gz]

bundle 解包后目录结构：
    mahjong-extractor/
      remote/extractor/*.py + config.yaml
      stable/{__init__,protocol,tracker,mapping}.py
      battle/{__init__,state}.py          # 不含 service.py(cv2)
      game/**                              # 整个 game 包(无 cv2)
      utils/{__init__,paths}.py
      install_linux.sh  install_openwrt.sh
      files/mahjong-extractor.service  files/mahjong-extractor.init
      selfcheck_capture.sh  DEPLOY.md

Python 3.7+，仅用标准库。
"""
import argparse
import io
import os
import secrets
import sys
import tarfile

# 项目根 = 本文件上两级
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))

# extractor 运行时最小模块集（实测 stable.tracker 链 + 打包冗余安全项）
_INCLUDE_FILES = [
    # extractor 应用本身
    "remote/extractor/main.py",
    "remote/extractor/capture.py",
    "remote/extractor/token_extractor.py",
    "remote/extractor/uploader.py",
    "remote/extractor/config.yaml",
    # stable 协议/状态
    "stable/__init__.py",
    "stable/protocol.py",
    "stable/tracker.py",
    "stable/mapping.py",
    # battle：只要 state（懒加载后不再连带 service.py/cv2）
    "battle/__init__.py",
    "battle/state.py",
    # utils
    "utils/__init__.py",
    "utils/paths.py",
]

# 整目录纳入（game 包较小且全为纯 python，避免漏掉懒加载路径）
_INCLUDE_DIRS = [
    "game",
]

# 目录纳入时排除这些（heavy / 无关）
_DIR_EXCLUDE_SUFFIX = (".pyc",)
_DIR_EXCLUDE_PART = ("__pycache__", )

# bundle 内附带的部署资产（相对 remote/extractor/，打到 bundle 根）
_ASSET_FILES = [
    "install_linux.sh",
    "install_openwrt.sh",
    "selfcheck_capture.sh",
    "DEPLOY.md",
    "files/mahjong-extractor.service",
    "files/mahjong-extractor.init",
]

_TOP = "mahjong-extractor"  # bundle 顶层目录

# strongSwan VPN 部署资产（相对 remote/extractor/vpn/，打到 bundle 顶层 vpn/）
_VPN_ASSET_FILES = [
    "install_vpn.sh",
    "portal.py",
    "README.md",
]


def _iter_dir(rel_dir):
    base = os.path.join(_ROOT, rel_dir)
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in _DIR_EXCLUDE_PART]
        for fn in filenames:
            if fn.endswith(_DIR_EXCLUDE_SUFFIX):
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, _ROOT).replace(os.sep, "/")
            yield rel


def _add(tar, abs_path, arcname):
    tar.add(abs_path, arcname=arcname, recursive=False)


def _add_bytes(tar, data, arcname):
    encoded = data.encode("utf-8")
    info = tarfile.TarInfo(arcname)
    info.size = len(encoded)
    tar.addfile(info, io.BytesIO(encoded))


def _read_simple_yaml(path):
    data = {}
    if not os.path.isfile(path):
        return data
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#") or ":" not in stripped:
                continue
            key, value = stripped.split(":", 1)
            value = value.strip().strip("'\"")
            data[key.strip()] = value
    return data


def _extractor_config(relay_url, api_token, game_port):
    return (
        "# Generated by package_extractor.py\n"
        "relay_url: \"{}\"\n"
        "api_token: \"{}\"\n"
        "game_port: {}\n"
    ).format(relay_url, api_token, int(game_port))


def _write_relay_config(path, api_token, game_server_ip, game_server_port):
    parent = os.path.dirname(os.path.abspath(path))
    if parent:
        os.makedirs(parent, exist_ok=True)
    data = (
        "# Generated by package_extractor.py\n"
        "api_token: \"{}\"\n"
        "game_server_ip: \"{}\"\n"
        "game_server_port: {}\n"
        "handshake_blob: \"\"\n"
        "auth_token_12b: \"\"\n"
    ).format(api_token, game_server_ip, int(game_server_port))
    with open(path, "w", encoding="utf-8") as f:
        f.write(data)


def _collect_vpn_files(args, api_token, game_server_ip, game_server_port):
    """Collect strongSwan IKEv2 VPN files for bundling.
    Returns list of (arcname, filepath_or_None, data_bytes_or_None).
    """
    import subprocess as _sp
    import tempfile as _tmp
    import shutil as _sh

    files = []
    vpn_dir = os.path.join(_HERE, "vpn")
    vpn_bundle_prefix = "{}/vpn".format(_TOP)

    # 1) Static assets
    for asset in _VPN_ASSET_FILES:
        src = os.path.join(vpn_dir, asset)
        if not os.path.isfile(src):
            print("[WARN] VPN 资产缺失（跳过）: {}".format(asset))
            continue
        arcname = "{}/{}".format(vpn_bundle_prefix, asset)
        files.append((arcname, src, None))

    # 2) vpn_configure.py
    vpn_configure_src = os.path.join(vpn_dir, "vpn_configure.py")
    if os.path.isfile(vpn_configure_src):
        arcname = "{}/vpn_configure.py".format(vpn_bundle_prefix)
        files.append((arcname, vpn_configure_src, None))
    else:
        print("[WARN] vpn_configure.py 缺失，跳过")

    # 3) Pre-generate VPN configs
    tmpdir = _tmp.mkdtemp(prefix="vpn_config_")
    try:
        cmd = [
            sys.executable, vpn_configure_src,
            "--server-ip", args.vpn_server_ip,
            "--game-server-ip", game_server_ip,
            "--output-dir", tmpdir,
        ]
        result = _sp.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode != 0:
            print("[WARN] vpn_configure.py 失败: {}".format(result.stderr.strip()))
            print("        VPN 配置将不会预生成，请部署后手动运行 vpn_configure.py")
        else:
            for cfg_name in ["ipsec.conf", "ipsec.secrets", "phone-setup.txt"]:
                cfg_path = os.path.join(tmpdir, cfg_name)
                if os.path.isfile(cfg_path):
                    with open(cfg_path, "r", encoding="utf-8") as f:
                        data = f.read()
                    arcname = "{}/{}".format(vpn_bundle_prefix, cfg_name)
                    files.append((arcname, None, data))
            print("[ok] VPN 配置已预生成: server={}".format(args.vpn_server_ip))
            print(result.stdout.strip())
    finally:
        _sh.rmtree(tmpdir, ignore_errors=True)

    print("[ok] VPN 模块已收集 (含 {} 个文件)".format(len(files)))
    print("     云端部署后按 vpn/README.md 指引配置 VPN 隧道")
    return files


def main():
    ap = argparse.ArgumentParser(description="Package extractor for soft-router deploy")
    ap.add_argument("-o", "--output", default=os.path.join(_ROOT, "mahjong-extractor-bundle.tar.gz"))
    ap.add_argument(
        "--relay-url",
        help="Preconfigure bundled extractor/config.yaml with the public relay URL, e.g. http://1.2.3.4:8000",
    )
    ap.add_argument(
        "--api-token",
        help="Shared API token. If omitted with --relay-url, a random token is generated and printed.",
    )
    ap.add_argument("--game-port", type=int, default=7777, help="Game TCP port to capture (default: 7777)")
    ap.add_argument(
        "--write-relay-config",
        help="Optional path to write a matching relay config.yaml for the cloud server.",
    )
    ap.add_argument(
        "--game-server-ip",
        default=None,
        help="Game server IP for --write-relay-config (default: value from remote/relay/config.yaml or 47.96.0.227)",
    )
    ap.add_argument(
        "--game-server-port",
        type=int,
        default=None,
        help="Game server port for --write-relay-config (default: value from remote/relay/config.yaml or 7777)",
    )
    ap.add_argument(
        "--with-vpn",
        action="store_true",
        help="Include strongSwan IKEv2 VPN tunneling support in the bundle (install_vpn.sh, vpn_configure.py, portal.py, README.md)",
    )
    ap.add_argument(
        "--vpn-server-ip",
        help="Cloud VM / router public IP for VPN server. Required when --with-vpn is set.",
    )
    args = ap.parse_args()

    api_token = args.api_token
    if args.relay_url and not api_token:
        api_token = secrets.token_hex(12)
    if args.with_vpn and not api_token:
        api_token = secrets.token_hex(12)
    if args.write_relay_config and not api_token:
        print("[ERROR] --write-relay-config requires --api-token or --relay-url")
        return 1
    if args.with_vpn and not args.vpn_server_ip:
        print("[ERROR] --with-vpn requires --vpn-server-ip <public_ip>")
        return 1

    config_override = None
    if args.relay_url:
        config_override = _extractor_config(args.relay_url, api_token, args.game_port)

    relay_defaults = _read_simple_yaml(os.path.join(_ROOT, "remote", "relay", "config.yaml"))
    game_server_ip = args.game_server_ip or relay_defaults.get("game_server_ip") or "47.96.0.227"
    game_server_port = args.game_server_port or relay_defaults.get("game_server_port") or 7777

    # 收集模块文件
    rels = []
    missing = []
    for rel in _INCLUDE_FILES:
        if os.path.isfile(os.path.join(_ROOT, rel)):
            rels.append(rel)
        else:
            missing.append(rel)
    for d in _INCLUDE_DIRS:
        rels.extend(_iter_dir(d))

    if missing:
        print("[ERROR] 缺少必要文件，打包中止：")
        for m in missing:
            print("   -", m)
        return 1

    out = args.output

    # 收集 VPN 文件（要在 tarball 创建阶段一起写入，gzip 不支持追加）
    vpn_files = []  # list of (arcname, filepath) or (arcname, None, bytes_data)
    if args.with_vpn:
        vpn_files = _collect_vpn_files(args, api_token, game_server_ip, game_server_port)

    with tarfile.open(out, "w:gz") as tar:
        # 1) 模块文件，保持包路径，放在 bundle 顶层目录下
        for rel in rels:
            arcname = "{}/{}".format(_TOP, rel)
            if rel == "remote/extractor/config.yaml" and config_override is not None:
                _add_bytes(tar, config_override, arcname)
            else:
                _add(tar, os.path.join(_ROOT, rel), arcname)
        # 2) 部署资产（从 remote/extractor/ 取，平铺到 bundle 顶层）
        for asset in _ASSET_FILES:
            src = os.path.join(_HERE, asset)
            if not os.path.isfile(src):
                print("[WARN] 部署资产缺失（跳过）:", asset)
                continue
            _add(tar, src, "{}/{}".format(_TOP, asset))
        # 3) 顶层 run 包装，便于 `python run.py`（设置 sys.path 到 bundle 顶层）
        run_py = (
            "import os, sys\n"
            "sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))\n"
            "from remote.extractor.main import main\n"
            "if __name__ == '__main__':\n"
            "    main()\n"
        )
        _add_bytes(tar, run_py, "{}/run.py".format(_TOP))

        # 4) VPN 文件（如果有）
        vpn_count = 0
        for arcname, src_path, data_bytes in vpn_files:
            if data_bytes is not None:
                _add_bytes(tar, data_bytes, arcname)
            else:
                _add(tar, src_path, arcname)
            vpn_count += 1
        if vpn_count > 0:
            print("[ok] VPN 模块已打包 (含 {} 个文件)".format(vpn_count))

    if args.write_relay_config:
        _write_relay_config(args.write_relay_config, api_token, game_server_ip, game_server_port)
        print("[ok] relay config written: {}".format(args.write_relay_config))

    size_kb = os.path.getsize(out) / 1024.0
    print("[ok] bundle 生成: {} ({:.1f} KB)".format(out, size_kb))
    print("[ok] 含模块 {} 个 + 部署脚本".format(len(rels)))
    if config_override is not None:
        print("[ok] bundled extractor relay_url={}".format(args.relay_url))
        print("API_TOKEN={}".format(api_token))
    print("下一步：scp {} 到路由器，解包后按 DEPLOY.md 执行 install_*.sh".format(os.path.basename(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
